[package]
name = "gh-stats"
version = "0.1.0"
authors = ["Matthias Endler <matthias-endler@gmx.net>"]
edition = "2018"

[dependencies]
anyhow = "1.0.36"
tokio = { version = "1.0.0", features = ["macros", "rt-multi-thread"] } 
tokio-stream = "0.1.0"
structopt = "0.3.21"
regex = "1.4.2"
tera = "1.6.0"
hubcaps = { git = "https://github.com/mre/hubcaps", branch="master"}
